### PR TITLE
Propagating changes from USGS-Astro fork

### PR DESCRIPTION
**Pull request by Kelvinrr**
This fixes the version bug mentioned in #21 but also includes updates to the tests. It also updates travis.yaml to do an Anaconda-based installation and added an anaconda recipe. 

@wtolson there is also a pysis-feedstock open here: https://github.com/conda-forge/pysis-feedstock, Let me know if you want to be a maintainer. Otherwise, I don't think anyone at USGS-Astro would be bothered by adopting the repo since we use pysis quite a bit.

### CODE REVIEW

**Comment by wtolson** [comment]
Thanks @Kelvinrr, this looks great! I did notice the author email and url was changed in `setup.py`.

**Comment by Kelvinrr** [comment]
That's an oof, definitely a mistake.

**Comment by wtolson** [comment]
@Kelvinrr Thanks again for the MR. Great to hear you guys are getting use out of it. As per pysis-feedstock, I unfortunately don't get a lot of time to work on this stuff anymore so I'm good with anyone who wants to maintain it. Also want to loop in @michaelaye as he's done a ton to maintain pysis over the years. Also open to moving pysis officially under the USGS-Astro namespace if you guys want to maintain and get you guys push access on PyPI. Thanks and let me know your thoughts.

**Comment by wtolson** [comment]
Also check out https://github.com/planetarypy. I moved pvl (which spun out of pysis) into that namespace a while ago. @godber or @pbvarga1 might know who's maintaining that at the moment too.

**Comment by michaelaye** [comment]
Let's say, I'm more an efficient bug reporter than a maintainer. ;) I think I made it to 1 or 2 pull requests?

**Pull request merged**
