### PR TITLE
adding little check to open fname strings automatically in constructo…

### LINKED ISSUE #11: Proposition:
I propose to change CubeFile to examine the input type, and if it's a string, to automatically open the filestream. This, to avoid the, IMHO, cumbersome CubeFile.open API.
If you agree, I can do a PR?

Edited: i confused my derived class RingCube with your CubeFile class.

### PR DESCRIPTION
**Pull request by michaelaye**
…r. Fixes #11 
Finally got round to it.

### CODE REVIEW

**Comment by wtolson** [comment]
Thanks @michaelaye! Looks like some of the tests are failing, would you be able to look into that? We'll also want to make sure we close any files that we open. Other that it looks good to me.

**Comment by michaelaye** [comment]
I fixed an obvious bug, but have no clue about the other test failures?

```bash
FileNotFoundError: [Errno 2] No such file or directory: 'isis_echo'
```

Looks a bit like a localized testing bug?

**Comment by michaelaye** [comment]
Actually, this test I have to remove,  I guess?
```python
   def test_stream_error():
        with pytest.raises(TypeError):
>           CubeFile('filename.cub')
```

**Comment by michaelaye** [comment]
okay, so Travis passes, but locally I still fail the tests with above mentioned `isis_echo` error.

**Comment by wtolson** [comment]
Thanks again @michaelaye. I think locally your test isis environment is not getting setup. Try running the tests with the command  `make test`.

**Comment by michaelaye** [comment]
That's correct, `make test` passes.

**Pull request merged**
